auth_enabled: false
  enable_alertmanager_v2: true
  enable_api: true
      directory: /loki/rules
    local:
    type: local
  storage:
  rule_path: /loki/rules-temp
      store: inmemory
    kvstore:
  ring:
  alertmanager_url: http://localhost:9009/alertmanager
ruler:

  retention_period: 0s
  retention_deletes_enabled: false
table_manager:

  max_look_back_period: 0s
chunk_store_config:

  max_query_parallelism: 32
  max_query_series: 100000
  ingestion_burst_size_mb: 32
  ingestion_rate_mb: 16
  reject_old_samples_max_age: 168h
  reject_old_samples: true
limits_config:

  shared_store: filesystem
  working_directory: /loki/boltdb-shipper-compactor
compactor:

    directory: /loki/chunks
  filesystem:
    shared_store: filesystem
    cache_ttl: 24h
    cache_location: /loki/boltdb-shipper-cache
    active_index_directory: /loki/boltdb-shipper-active
  boltdb_shipper:
storage_config:

        period: 24h
        prefix: index_
      index:
      schema: v11
      object_store: filesystem
      store: boltdb-shipper
    - from: 2020-10-24
  configs:
schema_config:

      store: inmemory
    kvstore:
    instance_addr: 127.0.0.1
  ring:
  replication_factor: 1
      rules_directory: /loki/rules
      chunks_directory: /loki/chunks
    filesystem:
  storage:
  path_prefix: /loki
common:

  grpc_listen_port: 9096
  http_listen_port: 3100
server:


