apiVersion: 1
        enabled: true
      nodeGraph:
        datasourceUid: Mimir
      serviceMap:
        filterBySpanID: false
        filterByTraceID: false
        spanEndTimeShift: '1h'
        spanStartTimeShift: '1h'
        mapTagNamesEnabled: true
        mappedTags: [{ key: 'service.name', value: 'service' }]
        tags: ['job', 'instance', 'pod', 'namespace']
        datasourceUid: Loki
      tracesToLogs:
      httpMethod: GET
    jsonData:
    editable: true
    url: http://tempo:3200
    access: proxy
    type: tempo
  - name: Tempo

      maxLines: 1000
    jsonData:
    editable: true
    url: http://loki:3100
    access: proxy
    type: loki
  - name: Loki

      prometheusType: Mimir
      manageAlerts: true
      httpMethod: POST
    jsonData:
    editable: true
    isDefault: true
    url: http://mimir:9009/prometheus
    access: proxy
    type: prometheus
  - name: Mimir
datasources:


